### ISSUE TITLE
计划任务运行bat文件，无法转移到对应文件夹

### ISSUE THREAD

**Issue by curtin18** [QinHuoBin/auto_login_ipgw#1]
在win10和win11环境下运行，用计划任务运行bat文件，无法转移到对应文件夹，只能在C:\windows\system32中运行。
经查找发现，需在运行python前添加相应路径
set base_dir=%~dp0

%base_dir:~0,2%

pushd %base_dir%
![bat](https://github.com/QinHuoBin/auto_login_ipgw/assets/65641029/bd937def-fd52-46d8-8e99-d088df526f9f)

**Comment by QinHuoBin** [comment]
我这里运行是正常的，但感谢您的提出
